#!/bin/sh

# REQUIRE: LOGIN FILESYSTEMS

. /etc/rc.subr

name=jdownloader
rcvar=`set_rcvar`
command="java"
command_args=" -Djava.awt.headless=true -jar JDownloader.jar"
start_cmd="/usr/sbin/daemon $command $command_args"

cd /usr/share/local/jdownloader

load_rc_config $name
run_rc_command "$1"
